apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blog-frontend
  namespace: blog
  labels:
    app: frontend
    version: "${VERSION}"
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-${VERSION}
  targetCPUUtilizationPercentage: 80
