apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blog
  labels:
    app: frontend
spec:
  selector:
    app: frontend
    version: "${VERSION}"
  ports:
  - port: 8080
    targetPort: 3000
