version: '3.7'

services:
  ingress:
    build: 
      context: .
      dockerfile: ops/docker/ingress/Dockerfile
    volumes:
    - ./ops/docker/helpers/openssl/certs:/etc/nginx/certs:ro
    ports:
    - 80:80
    - 443:443
    networks:
    - app
    extra_hosts:
    - "eden-reich.com dev.eden-reich.com dev-admin.eden-reich.com:127.0.0.1"
    depends_on: 
    - openssl
    
  frontend:
    build:
      target: development
      args:
        APP_ENV: development
      context: .
      dockerfile: ops/docker/frontend/Dockerfile
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
    volumes:
    - ./src/frontend:/app:rw
    networks:
    - app
    extra_hosts:
    - "eden-reich.com dev.eden-reich.com dev-admin.eden-reich.com:127.0.0.1"

  admin:
    build:
      target: development
      args:
        NODE_ENV: development
      context: .
      dockerfile:  ops/docker/admin/Dockerfile
    volumes:
    - ./src/admin:/app:rw
    networks: 
    - app
    extra_hosts:
    - "eden-reich.com dev-admin.eden-reich.com:127.0.0.1"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blog
    ports:
    - 5432:5432
    networks:
    - app
    volumes:
    - ./src/admin/database:/docker-entrypoint-initdb.d
    - database-data:/var/lib/postgresql/data

  openssl:
    build:
      context: .
      dockerfile: ops/docker/helpers/openssl/Dockerfile
    volumes:
    - ./ops/docker/helpers/openssl/certs:/root/certs:rw

  npm:
    image: node:14-buster-slim
    command:
    - /bin/bash 
    - -c
    - |
      if [ ! -d /frontend/node_modules ]; then
        apt-get update;
        apt-get install -y build-essential python;
        yarn;
      fi
      if [ ! -d /admin/node_modules ]; then 
        apt-get update apt-get install -y build-essential python;
        cd /admin;
        yarn;
      fi
    working_dir: /frontend
    volumes:
    - ./src/frontend:/frontend:rw
    - ./src/admin:/admin:rw

volumes:
  database-data:

networks:
  app: