version: '3.7'

services:
  ingress:
    build: 
      context: .
      dockerfile: ops/docker/ingress/Dockerfile
    volumes:
    - ./ops/docker/helpers/openssl/certs:/etc/nginx/certs:ro
    ports:
    - 80:80
    - 443:443
    networks:
    - app
    extra_hosts:
    - "eden-reich.com dev.eden-reich.com dev-admin.eden-reich.com:127.0.0.1"
    depends_on: 
    - openssl
    
  frontend:
    build:
      target: development
      args:
        APP_ENV: development
      context: .
      dockerfile: ops/docker/frontend/Dockerfile
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
    volumes:
    - ./src/frontend:/app:rw
    networks:
    - app
    extra_hosts:
    - "eden-reich.com dev.eden-reich.com dev-admin.eden-reich.com:127.0.0.1"

  admin:
    build:
      target: development
      args:
        APP_ENV: development
      context: .
      dockerfile:  ops/docker/admin/Dockerfile
    volumes:
    - ./src/admin:/app:rw
    networks: 
    - app
    extra_hosts:
    - "eden-reich.com dev-admin.eden-reich.com:127.0.0.1"
  
  openssl:
    build:
      context: .
      dockerfile: ops/docker/helpers/openssl/Dockerfile
    volumes:
    - ./ops/docker/helpers/openssl/certs:/root/certs:rw


networks:
  app: