apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend-{{VERSION}}
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-frontend-{{VERSION}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blog-frontend-{{VERSION}}
    spec:
      containers:
      - name: blog-frontend
        image: edenr/stage-blog-frontend:latest
        resources:
          requests:
            cpu: "200m"
            memory: "499Mi"
          limits:
            cpu: "200m"
            memory: "499Mi"
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: blog-environment
              key: app_env
        - name: MAILGUN_DOMAIN
          valueFrom:
            secretKeyRef:
              name: mailgun
              key: domain
        - name: MAILGUN_API_KEY
          valueFrom:
            secretKeyRef:
              name: mailgun
              key: api_key
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
        livenessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: regcred
