apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api
  namespace: blog
data:
  database_url: <BASE64 ENCODED STRING>
  jwt_passphrase: <BASE64 ENCODED STRING>
  jwt_public_key: <BASE64 ENCODED STRING>
  jwt_secret_key: <BASE64 ENCODED STRING>
  test_database_url: <BASE64 ENCODED STRING>
  google_application_credentials: <BASE64 ENCODED STRING>
