apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: latest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
        version: latest
    spec:
      containers:
      - name: frontend
        image: k3d-registry.internal:5000/frontend:latest
        resources:
          requests:
            cpu: "1"
            memory: 499Mi
          limits:
            cpu: "1"
            memory: 499Mi
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend
              key: app_env
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              name: frontend
              key: api_username
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: frontend
              key: api_password
        - name: MAILGUN_DOMAIN
          valueFrom:
            secretKeyRef:
              name: frontend
              key: mailgun_domain
        - name: MAILGUN_API_KEY
          valueFrom:
            secretKeyRef:
              name: frontend
              key: mailgun_api_key
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            port: 3000
            path: /api/healthcheck
        livenessProbe:
          httpGet:
            port: 3000
            path: /api/healthcheck
        imagePullPolicy: Always
        volumeMounts:
        - name: frontend-volume
          mountPath: /app
      terminationGracePeriodSeconds: 60
      volumes:
      - name: frontend-volume
        hostPath:
          path: /app/frontend
