apiVersion: v1
kind: Secret
metadata:
  name: frontend
  namespace: blog
type: Opaque
data:
  api_username: YWRtaW5AZ21haWwuY29t
  api_password: YWRtaW4=
  mailgun_api_key: dGVzdA==
  mailgun_domain: bWcuZWRlbi1yZWljaC5jb20=
