apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-${VERSION}
  namespace: blog
  labels:
    app: api
    version: "${VERSION}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: "${VERSION}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
        version: "${VERSION}"
    spec:
      containers:
      - name: api
        image: ${REPOSITORY}:${VERSION}
        env:
        - name: JWT_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: api
              key: jwt_passphrase
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api
              key: jwt_secret_key
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: api
              key: jwt_public_key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api
              key: database_url
        resources:
          requests:
            cpu: "200m"
            memory: "499Mi"
          limits:
            cpu: "200m"
            memory: "499Mi"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /api/v1/healthcheck
        livenessProbe:
          httpGet:
            port: 8080
            path: /api/v1/healthcheck
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: regcred
