apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: blog
  labels:
    app: admin
spec:
  selector:
    app: admin
    version: "${VERSION}"
  ports:
  - port: 8080
    targetPort: 3000
