apiVersion: batch/v1
kind: Job
metadata:
  name: admin-linting-${VERSION}
  namespace: blog
  labels:
    app: admin
    version: "${VERSION}"
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: admin-linting
        image: ${REPOSITORY}:${VERSION}
        resources:
          requests:
            cpu: 499m
            memory: 499Mi
          limits:
            cpu: 499m
            memory: 499Mi
        command: [ "/bin/sh", "-c", "bin/console lint:yaml config && ./vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run --verbose" ]
      restartPolicy: Never
      imagePullSecrets:
      - name: container-registry
  backoffLimit: 1
