apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
  - hosts:
    - stage.eden-reich.com
    - stage-admin.eden-reich.com
    secretName: eden-reich.com-tls
  rules:  
    - host: stage.eden-reich.com
      http:
        paths:
        - path: /
          backend:
            serviceName: blog-frontend
            servicePort: 8080
    - host: stage-admin.eden-reich.com
      http:
        paths:
        - path: /
          backend:
            serviceName: blog-admin
            servicePort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress-controller
  namespace: kube-system
data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  use-proxy-protocol: "false"
  server-snippet: |
    real_ip_header CF-Connecting-IP;
