apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: admin
  namespace: blog
  labels:
    app: admin
    version: "${VERSION}"
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-${VERSION}
  targetCPUUtilizationPercentage: 50
