name: admin

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/admin.yml"
      - "src/admin/**"
      - "ops/docker/admin/**"
      - "ops/kubernetes/deployments/admin/**"

env:
  DOCKER_IMAGE_NAME: blog-admin
  DOCKER_REPO: edenr/blog-admin
  DEPLOYMENT_NAME: blog-admin
  DEPLOYMENT_VERSION: ${{ github.run_number }}
  SERVERS: k4s-master k4s-node1 k4s-node2 k4s-node3 k4s-node4

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Docker Build
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --target production \
            --build-arg APP_ENV=production \
            -t ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }} \
            -t ${{ env.DOCKER_REPO }}:latest \
            -f ops/docker/admin/Dockerfile .
  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Docker Push
        run: |
          docker push ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
          docker push ${{ env.DOCKER_REPO }}:latest
  deploy:
    runs-on: self-hosted
    needs: push
    steps:
      - uses: actions/checkout@master
      - name: Deploy to Kubernetes
        run: |
          kubectl config use-context production
          kubectl apply -f ops/kubernetes/deployments/admin/
          kubectl patch deployment ${{ env.DEPLOYMENT_NAME }} -p '{"spec":{"template":{"spec":{"containers":[{"name":"${{ env.DOCKER_IMAGE_NAME }}","image":"${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}"}]}}}}'
  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Remove all images from github-runner
        run: docker rmi -f $(docker images -q) 2> /dev/null || true
      - name: Keep 5 Releases
        run: for server in $(echo ${{ env.SERVERS }} | xargs); do ssh -v $server ./scripts/cleanup.sh ${{ env.DOCKER_REPO }}; done
      - name: Remove Dangling Docker Images
        run: docker system prune -f
