name: build

on: [push]

env:
  DOCKER_REPO: edenr/blog
  VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Docker Build
      run: |
        docker build \
          --build-arg MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }} \
          -t ${{ env.DOCKER_REPO }}:latest \
          -f ops/docker/blog/Dockerfile .
    - name: Docker Tag
      run: docker tag ${{ env.DOCKER_REPO }}:latest ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
  push:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Push
      run: |
        docker push ${{ env.DOCKER_REPO }}:latest
        docker push ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
  deploy:
    runs-on: self-hosted
    needs: push
    steps:
    - uses: actions/checkout@master
    - name: Kubernetes Apply
      run: |
        KUBECONFIG=/home/pi/.kube/config kubectl patch deployment blog -p '{"spec":{"template":{"spec":{"containers":[{"name":"blog","image":"${{ env.DOCKER_REPO }}:${{ env.VERSION }}"}]}}}}'
  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
    - name: Keep 5 Releases
      run: docker rmi $(docker images | grep edenr/blog | sort -r | tail -n +6 | awk '{ printf "%s\t", $3 }' | xargs) || true
    - name: Remove Dangling Docker Images
      run: docker system prune -f