name: frontend

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/frontend.yml"
      - "src/frontend/**"
      - "ops/docker/frontend/**"
      - "ops/kubernetes/frontend/**"

env:
  DOCKER_BUILDKIT: 1
  DOCKER_REPO: edenr/blog-frontend
  DEPLOYMENT_NAME: blog-frontend
  DEPLOYMENT_VERSION: ${{ github.run_number }}
  SERVERS: k4s-master k4s-node1 k4s-node2 k4s-node3 k4s-node4
  ARTIFACT_FILES: src/frontend/package.json ops/docker/frontend/artifacts/Dockerfile

jobs:
  check:
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Check if relevant artifact files have been changed
        id: check_files
        run: |
          for file in $(echo ${{ env.ARTIFACT_FILES }} | xargs); do
            if [ $(git diff --name-only HEAD^ HEAD | grep $file) ]; then 
              echo "::set-output name=run_job::true"
              break
            else
              echo "::set-output name=run_job::false"
            fi
          done
  build-artifacts:
    runs-on: self-hosted
    needs: check
    steps:
      - uses: actions/checkout@master
      - name: Build Artifacts
        if: ${{ needs.check.outputs.run_job == 'true' }}
        run: |
          docker build \
            -t frontend-artifacts:latest \
            -f ops/docker/frontend/artifacts/Dockerfile .
  build:
    runs-on: self-hosted
    needs: build-artifacts
    steps:
      - uses: actions/checkout@master
      - name: Docker Build
        run: |
          docker build \
            --target production \
            --cache-from ${{ env.DOCKER_REPO }}:latest \
            -t ${{ env.DOCKER_REPO }}:latest \
            -f ops/docker/frontend/Dockerfile .
      - name: Docker Tag Image
        run: |
          docker tag ${{ env.DOCKER_REPO }}:latest ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Docker Push
        run: |
          docker push ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
          docker push ${{ env.DOCKER_REPO }}:latest
  deploy:
    runs-on: self-hosted
    needs: push
    steps:
      - uses: actions/checkout@master
      - name: Kubernetes - switch to production context
        run: kubectl config use-context production
      - name: Kubernetes - create a new deployment
        run: cat ops/kubernetes/frontend/deployment.yaml | sed "s/{{VERSION}}/${{ env.DEPLOYMENT_VERSION }}/g" | kubectl apply -f -
      - name: Kubernetes - wait for new deployment to be successfully rolled out
        run: |
          max_count=180
          count=0
          while [ true ]; do
            if [[ $count -gt $max_count ]]; then
              echo "===> Waited for too long for a successful rolled out green version, but something went wrong. Aborting..."
              exit 1
            fi
            if [[ $(kubectl rollout status deploy/${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} | grep 'successfully rolled out') ]]; then
              break
            fi
            count=$((count+1))
            echo "===> New deployment ${{ env.DEPLOYMENT_NAME }}-${{ env.DEPLOYMENT_VERSION }} is being rollout out..."
            sleep 1
          done
      - name: Kubernetes - apply horizontal pods autoscaling to new deployment
        run: cat ops/kubernetes/frontend/hpa.yaml | sed "s/{{VERSION}}/${{ env.DEPLOYMENT_VERSION }}/g" | kubectl apply -f -
      - name: Kubernetes - switch LB to green deployment
        run: cat ops/kubernetes/frontend/service.yaml | sed "s/{{VERSION}}/${{ env.DEPLOYMENT_VERSION }}/g" | kubectl apply -f -
  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Remove all related images from github-runner except latest
        run: docker rmi -f $(docker images | grep ${{ env.DOCKER_REPO }} | grep -v latest | awk '{image = sprintf("%s:%s", $1,$2)} END {print image}' | xargs) || true
      - name: Remove Dangling Docker Images
        run: docker system prune -f
      - name: Keep 5 container images
        run: for server in $(echo ${{ env.SERVERS }} | xargs); do ssh $server ./scripts/cleanup.sh; done
      - name: Keep 3 deployments available for rollback
        run: kubectl delete deployments $(kubectl get deployments | grep ${{ env.DEPLOYMENT_NAME }} | awk '{ print $1 }' | sort -rn | tail -n+4) || true
