name: frontend

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/frontend.yml"
      - "src/frontend/**"
      - "ops/docker/frontend/**"
      - "ops/kubernetes/deployments/frontend/**"

env:
  DOCKER_IMAGE_NAME: blog-frontend
  DOCKER_REPO: edenr/blog-frontend
  DEPLOYMENT_NAME: blog-frontend
  DEPLOYMENT_VERSION: ${{ github.run_number }}
  SERVERS: k4s-master k4s-node1 k4s-node2 k4s-node3 k4s-node4

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Docker Build
        run: |
          DOCKER_BUILDKIT=1 docker build \
            -t ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }} \
            -t ${{ env.DOCKER_REPO }}:latest \
            -f ops/docker/frontend/Dockerfile .
  push:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Docker Push
        run: |
          docker push ${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}
          docker push ${{ env.DOCKER_REPO }}:latest
  deploy:
    runs-on: self-hosted
    needs: push
    steps:
      - uses: actions/checkout@master
      - name: Kubernetes Apply
        run: |
          kubectl config use-context production
          kubectl apply -f ops/kubernetes/deployments/frontend/
          kubectl patch deployment ${{ env.DEPLOYMENT_NAME }} -p '{"spec":{"template":{"spec":{"containers":[{"name":"${{ env.DOCKER_IMAGE_NAME }}","image":"${{ env.DOCKER_REPO }}:${{ env.DEPLOYMENT_VERSION }}"}]}}}}'
  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Remove all images from github-runner
        run: docker rmi -f $(docker images -q)
      - name: Keep 5 Releases
        run: for server in ${{ env.SERVERS }}; do ssh $server /bin/sh -c 'docker rmi $(docker images | grep ${{ env.DOCKER_REPO }} | sort -r | tail -n +6 | awk \'{ printf "%s\t", $3 }\' | xargs) || true'; done
      - name: Remove Dangling Docker Images
        run: docker system prune -f
