name: frontend-stage

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/frontend-stage.yml"
      - "src/frontend/**"
      - "ops/docker/frontend/**"
      - "ops/kubernetes/deployments/frontend/**"

env:
  DOCKER_IMAGE_NAME: blog-frontend
  DOCKER_REPO: edenr/blog-frontend
  DEPLOYMENT_NAME: blog-frontend
  DEPLOYMENT_VERSION: ${{ github.run_number }}
  SERVERS: k8s-master k8s-node1 k8s-node2 k8s-node3

jobs:
  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Remove all images from github-runner
        run: docker rmi -f $(docker images -q)
      - name: Keep 5 Releases
        run: for server in "${{ env.SERVERS }}"; do ssh -v $server /bin/sh -c "docker rmi \$(docker images | grep ${{ env.DOCKER_REPO }} | sort -r | tail -n +6 | awk '{ printf \"%s\t\", $3 }' | xargs) || true"; done
      - name: Remove Dangling Docker Images
        run: docker system prune -f
