apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication
  name: authentication
  namespace: blog
spec:
  selector:
    app: authentication
    version: "${VERSION}"
  ports:
  - port: 8080
    targetPort: 3000
